### ISSUE TITLE
How to get certains postType as item of a menu with Gatsby and Prismic?

### ISSUE THREAD

**Issue by Steffi3rd** [LekoArts/gatsby-starter-prismic#10]
Hi!

I would like to generate dynamically a header menu using custom type created on Prismic.
I have more than 12 categories (photos, posts, author, videos, gif, podcasts, images, case etc...)

And I would like to display only few of them, only the main categories like (posts, videos)

The idea is to display like this : (Actually It's manual)

<img width="458" alt="capture d ecran 2018-11-29 a 17 20 26" src="https://user-images.githubusercontent.com/814410/49236970-8648e600-f3fd-11e8-811d-d9ac99ebfec7.png">

My question are : 
- Is there a way to get these items using GraphQL query?
- And is it possible to add some tags or whatever to pick only few categories to display in this header menu?

Thanks!

**Comment by LekoArts** [comment]
Please have a look at the repository. I use Prismic to create the Hero Links (Could also be a navigation):
https://github.com/LekoArts/gatsby-starter-prismic/blob/master/.prismic/hero_links.json
Just add another field to the custom type, you then can filter on.
