### ISSUE TITLE
What is the GraphQL query to get all type of CustomType? (Prismic + Gatsby)

### ISSUE THREAD

**Issue by Steffi3rd** [LekoArts/gatsby-starter-prismic#11]
Hi, 

Is it possible to return all type of Custom Type? 

I created many custom types (post, videos, images, podcast etc...) and I would like to get these names in one query with GraphQL and Prismic?

Thanks

**Comment by LekoArts** [comment]
No, I don't think this is possible. To get a definite answer you should contact Prismic's support.
