### ISSUE TITLE
How absolute path works in this starter?

### ISSUE THREAD

**Issue by Steffi3rd** [LekoArts/gatsby-starter-prismic#12]
Hi, 

I have a question about path. 
It seems this starters use absolute paths. (eg: I can use 'components' instead of '../../components'

But I don't know where is configured.

The thing is I try to do the same thing on my new project (using Gatsby) but it doesn't work. So I'm wondering how this starter do this. 

Thanks

### Error 

```
This dependency was not found:

* OI in ./src/pages/app.js

To install it, you can run: npm install --save OI
```

**Comment by LekoArts** [comment]
Everything from `src` is absolute then:
https://github.com/LekoArts/gatsby-starter-prismic/blob/master/gatsby-node.js#L65-L72

**Comment by Steffi3rd** [comment]
Thanks @LekoArts! You rocks ;)
