### ISSUE TITLE
Handle localization ?

### ISSUE THREAD

**Issue by epegase** [LekoArts/gatsby-starter-prismic#15]
Dear @LekoArts ,

I want to add localization on my content in Prismic (multi-language content). 

Gatsby Starter Prismic handle localization ? I don't see this in features section.

Thanks you for all your work.

**Comment by epegase** [comment]
Another feature : search bar for posts ?

**Comment by LekoArts** [comment]
Hi, thank you for the questions!

Creating starters is always the struggle between being too barebone or too opinionated. I want to keep this starter as a general Prismic starter and i18n will complicate things a lot. You can have a look at my portfolio for a Prismic + i18n example: https://github.com/LekoArts/portfolio

As for the search: Kinda the same arguments as above. I don't feel like this is essential for every user. The documentation writes about that: https://www.gatsbyjs.org/docs/adding-search/

**Comment by LekoArts** [comment]
I now added a i18n version of this starter: https://github.com/LekoArts/gatsby-starter-prismic-i18n
