### ISSUE TITLE
Prismic Rich Text Links and rel="noopener noreferrer"

### ISSUE THREAD

**Issue by AllanPooley** [LekoArts/gatsby-starter-prismic#56]
Hello,

Firstly, thank you for making these starters @LekoArts! They've been pivotable to getting started with and adopting of Gatsby.

I have an issue, which I'm not sure belongs here, but I thought I would field it for discussion. (Maybe it's more appropriate to file in [gatsby-source-prismic](https://github.com/angeloashmore/gatsby-source-prismic) or taking up with Prismic directly).

I use the 'Rich Text Field' in Prismics most often for my blog posts. For example [this one](https://www.littleandbig.com.au/blog/building-with-gatsby/). They include links, which render as anchor tags, pointing off site to references and additional information.

All of these links have `target="_blank"` (toggleable in Prismic) to open them in a new tab. In past I've always added `rel="noopener noreferrer"` as a precaution after reading about "[tab nabbing](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)" and after WordPress rolled out this practice across their CMS.

There doesn't seem to be an easy way to configure the `rel` attribute for links inside of Prismic Rich Text Fields from my end. Do you have any ideas or insights on this challenge?

**Comment by AllanPooley** [comment]
Update

Some input from the Prismic product team:

> you should actually be able to take care of this on your own. I can see that the starter project uses the prismic-reactjs kit. When using this kit, you can use an HTML Serializer to modify the default output of the JSX/HTML. Here is the documentation for how to do this:
> [https://prismic.io/docs/reactjs/beyond-the-api/html-serializer](https://prismic.io/docs/reactjs/beyond-the-api/html-serializer)
> 
> Using an HTML Serializer, you can add the rel="noopener noreferrer" attribute to your links.

I might get a chance to work this in in the coming weeks, in which case I'll endeavour to make a pull request!

**Comment by LekoArts** [comment]
Hi!
I'm quite busy right now, so sorry that I didn’t answer earlier. What Prismic wrote is also what I'd propose to do:

https://github.com/LekoArts/gatsby-starter-prismic/blob/master/src/gatsby/htmlSerializer.js

Add a new case for links here and modify the output :) Would really appreciate at PR from you! If you have questions please let me know 😊
If you open a PR in a WIP state you'll get Netlify Previews and Cypress Tests so be sure to open that early if you want that tests to be run

**Comment by AllanPooley** [comment]
Hey @LekoArts I've submitted a pull request, please let me know if it looks OK to you.

Sorry it took so long!

**Comment by LekoArts** [comment]
Answered in your PR. Thanks for the issue and PR!
