### ISSUE TITLE
I'm using Slices, why GraphQL cannot query on field 'body'? 

### ISSUE THREAD

**Issue by Steffi3rd** [LekoArts/gatsby-starter-prismic#6]
I'm trying a query which returns the good result but I would like to know why GraphiQL show an error in the query, please? 

Same thing with `... on PrismicPostBodyQuote`

![capture d ecran 2018-11-09 a 12 32 19](https://user-images.githubusercontent.com/814410/48260416-b105d700-e41b-11e8-8044-6afff4b903e1.png)

**Comment by LekoArts** [comment]
Can't reproduce this error on my project. Try re-doing your query in GraphiQL.

![image](https://user-images.githubusercontent.com/16143594/48266303-465e9680-e42f-11e8-92a9-bb0409cd28fb.png)

**Comment by Steffi3rd** [comment]
Don't know why. Seems working now.
