### ISSUE TITLE
Changes coming from Prismic.io.

### ISSUE THREAD

**Issue by golfhotel** [LekoArts/gatsby-starter-prismic#7]
I'm testing this Gatsby Starter on Netlify. Everything went well: continuous development on Netlify works with the contents of the **GitHub repository**, but it seems that the contents coming from Prismic.io (when I update a post) are not updated; I have to do new launch of **Deploy site** on Netlify. Any suggestion?  

PS. Just to inform other users, on Netlify (in the **Deploy settings** area) it is necessary to compile the **Build command** field (writing `gatsby build`) and the **Publish directory** field (writing `public/`) as well as insert the **API_KEY** coming from Prismic. 

Thank you for this wonderful project.

**Comment by golfhotel** [comment]
I found a solution by configuring the **Webhook** on Prismic and the **Build Hook** on Netlify. But it's a bit slow as a mode. If there are any faster alternatives, I would be happy to know them.

**Comment by LekoArts** [comment]
Yeah, that's what I also described in the guide: https://www.gatsbyjs.org/docs/sourcing-from-prismic/#deploying-to-netlify

> But it's a bit slow as a mode.

How is that slow?

**Comment by golfhotel** [comment]
Yes. The guide was a great help. The mode is slow because since you update the content on Prismic and until you have the complete building on Netlify passes at least 1 minute or more.  It's a bit of a long wait, especially for publishers who continually change the contents.

**Comment by LekoArts** [comment]
That's just how it is with Gatsby, it's still a static site generator. You only can use the Preview feature in dev mode: https://github.com/birkir/gatsby-plugin-prismic-preview

**Comment by golfhotel** [comment]
Great. With this plugin, can I use Netlify as **Build/Preview Server**?

**Comment by LekoArts** [comment]
Probably, yes. But you should ask that the author of the plugin I guess.

**Comment by golfhotel** [comment]
In any case, I will report any positive evidence here. Thanks again!!!
