### ISSUE TITLE
Failing to compile on startup.

### ISSUE THREAD

**Issue by JABedford** [LekoArts/gatsby-starter-prismic#8]
Great starter theme! Really excited to get going with it, however I have an issue which I can't seem to solve! 

This is the issue I am getting. It logs in the terminal but after the error is thrown it states it "compiles correctly", however going to `localhost:8000` displays this.

```shell
GraphQL Error Field "categories" is not defined by type prismicPostConnectionDataInputObject_2.

  file: /Users/jbedford/Documents/GitHub/jabedford/src/templates/category.jsx

   1 | 
   2 |   query CategoryPage($category: String!) {
   3 |     posts: allPrismicPost(
   4 |       sort: { fields: [data___date], order: DESC }
   5 |       filter: {
   6 |         data: {
>  7 |           categories: { elemMatch: { category: { document: { elemMatch: { data: { name: { eq: $category } } } } } } }
     |           ^
   8 |         }
   9 |       }
  10 |     ) {
  11 |       totalCount
  12 |       edges {
  13 |         node {
  14 |           uid
  15 |           data {
  16 |             title {
  17 |               text
```
I set up everything in Prismic correctly as per the Readme and have two categories defined so not sure why this is happening.

Thanks very much in advance.

**Comment by LekoArts** [comment]
Do you have assigned a category to at least one post?

**Comment by JABedford** [comment]
Thats exactly what it was.
Schoolboy error on my behalf.

**Comment by YaroslawBagriy** [comment]
> Do you have assigned a category (in the „Meta“ tab) to at least one post?

I did, yet I'm still getting the same error.
