### ISSUE TITLE
Unknown type "PrismicPostBodyText"

### ISSUE THREAD

**Issue by umxr** [LekoArts/gatsby-starter-prismic#82]
Hey, not really sure on how to fix this error.

GraphQL Error Unknown type "PrismicPostBodyText".

  file: /Users/umar/Desktop/Work/umarcodes/src/templates/post.jsx

  13 |         categories {
  14 |           category {
  15 |             document {
  16 |               data {
  17 |                 name
  18 |               }
  19 |             }
  20 |           }
  21 |         }
  22 |         body {
> 23 |           ... on PrismicPostBodyText {
     |                  ^
  24 |             slice_type
  25 |             id
  26 |             primary {
  27 |               text {
  28 |                 html
  29 |               }
  30 |             }
  31 |           }
  32 |           ... on PrismicPostBodyCodeBlock {
  33 |             slice_type

ive set up all the content slices in prismic, added API keys etc.

**Comment by phlppk** [comment]
Did you **publish** the content after saving?

**Comment by vasilenka** [comment]
@umxr please check the name of your content type, if you are using other than `post` as the name, then your query should match the name.

In my case, I am using `blog`, so the syntax is PrismicBlogBodyText.
