### ISSUE TITLE
[Question] How to get the author of post with his picture using GraphQL?

### ISSUE THREAD

**Issue by Steffi3rd** [LekoArts/gatsby-starter-prismic#9]
Hi,

I have a post on Prismic, and this post is written by an author. 
I would like to get the author of this post (name and photo portrait).

2 questions : 
- How to get the name + photo of the author using GraphQL (and Prismic)?
- What if I want to have multiples authors for one post, how to get them?

**Comment by LekoArts** [comment]
Hi,
please put more effort into your issues. I don’t understand what you ask for

**Comment by LekoArts** [comment]
Checkout this section of my guide:
https://www.gatsbyjs.org/docs/sourcing-from-prismic/#categories

Categories => Authors
Category => Author

Add a text field (name) and image field (photo) to the Author repeatable type.
Add a content relationship field to your post type in a group.

The video shows that 👍

**Comment by Steffi3rd** [comment]
Thanks man! Your solution worked!

The GraphQL query to get theses values (using GraphiQL of Gatsby) is :

```
PrismicTYPENAME {
    uid
    data {
      authors_group { . 
        author {
          document {
            data {
              name {
                text
              }
              portrait {
                url
              }
            }
          }
        }
      }
}
```


The GraphQL query using GraphiQL of Primsic is 

```
PrismicTYPENAME {
    uid
    data {
       authors_group {
            author {
              ... on Author {
                name
                portrait
              }
       }
    }
}
```
